version: '3.8'

services:
  # [1] Nginx (외부 요청을 받는 문지기)
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend-server
      - websocket-server
    networks:
      - backend-net
    restart: always

  # [2] Certbot (SSL 인증서 봇)
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # [3] Backend Server (AWS용)
  backend-server:
    # Docker Hub에서 이미지(image)를 가져옴
    image: docker.io/${DOCKER_USERNAME}/backend-server:${IMAGE_TAG:-latest}
    container_name: backend-server
    env_file:
      - ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_ADDRESS=0.0.0.0
    networks:
      - backend-net
    restart: always

  # [4] WebSocket Server (AWS용)
  websocket-server:
    image: docker.io/${DOCKER_USERNAME}/websocket-server:${IMAGE_TAG:-latest}
    container_name: websocket-server
    env_file:
      - ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - backend-net
    restart: always

networks:
  backend-net:
    driver: bridge